### ISSUE TITLE
How to inject RouterState other than "router" key

### ISSUE THREAD

**Issue by Hardtack** [supasate/connected-react-router#104]
I'm wondering how can I inject router's redux state other than `router` key when I use `connectRouter()`.

In case of _react-router-redux_, this can be done by adding combining reducer manually.

``` javascript
import { routerReducer } from "react-router-redux";
import { combineReducers } from "redux";
import fooReducer from "./foo"

export default combineReducers({
    foo: fooReducer,
    someRouterStateKeyOtherThanRouter: routerReducer,
});

```

**Comment by desperate-man** [comment]
As far as I can see it is not possible because the "router" key is hard-coded and is used to find the data at the **root** of the store, see this [line of code](https://github.com/supasate/connected-react-router/blob/83bc910d40699fdb3f16d9d469476ebec0ca2c50/src/ConnectedRouter.js#L29).
So the store shape should always look like this:
```
{
  foo: '',
  router: {
    location: {
      pathname: '/',
      search: '',
      hash: ''
    },
    action: 'POP'
  }
}
```
That would be a nice to have feature.

**Comment by miraage** [comment]
@supasate it would be great to have an export with the router state key.

**Comment by supasate** [comment]
v5.0.0 supports this. (Beware of the breaking change. Please see the release note https://github.com/supasate/connected-react-router/releases/tag/v5.0.0)
