### ISSUE TITLE
components re-mounted on query change

### ISSUE THREAD

**Issue by etylsarin** [supasate/connected-react-router#168]
Hi @supasate,
Thanks for this great utility, I just need to clarify how to work with the query parameters.
When I dispatch the push action, providing an object with a search string, then url in the address bar changes, however also all the components are re-mounted.
Is that intentional and FAD? I thought the query params change should not be treated as a new page from the router point of view as the path remains the same.
Or is it anyhow possible to control whether I want to re-mount everything or not?
Thanks a lot!

**Comment by Andrekra** [comment]
From what I understand is that, through the context api, when the url changes, the Route will create a new element (effectifly re-mounting/re-rendering the component)
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L71

I've solved it by instead of letting the Route get the location from the context, it gets it from a prop.
`import { connect } from 'react-redux'

import {
  Redirect as DisconnectedRedirect,
  Route as DisconnectedRoute,
  Switch as DisconnectedSwitch,
} from 'react-router-dom'

const mapStateToProps = state => ({
    location: state.router.location // connected-react-router
})

export const Redirect = connect(mapStateToProps)(DisconnectedRedirect)
export const Route = connect(mapStateToProps)(DisconnectedRoute)
export const Switch = connect(mapStateToProps)(DisconnectedSwitch)`

You should use these everywhere in the app and remove withRouter where you can. Using the Profiler of react toolbar helped me a lot.

**Comment by sgal** [comment]
@etylsarin Could you please provide a code example? I had similar issue, but with just `react-router` itself, not this particular library.

For example, if you're using `render` prop in `Route` component it will remount on every change.

```
// does not remount on path change
<Route path="/foo" render={MyComponent} />

// remounts on path change
<Route path="/foo" render={(routeProps) => <MyComponent {...routeProps} flag={true} />} />
```

**Comment by etylsarin** [comment]
So I realized that I have also problem with react-router not with this redux connector. All I needed to do was to change [route render method](https://reacttraining.com/react-router/web/api/Route/route-render-methods) to "render". 
Then, I needed to add the code @Andrekra provided above. After that it's started to work as expected.
