### ISSUE TITLE
Version 6.1.0 is broken

### ISSUE THREAD

**Issue by ahce** [supasate/connected-react-router#220]
- The action LOCATION_CHANGE is called after componentDidMount of the component, this causes my sagas to be canceled.
I use redux-saga and cancel them with LOCATION_CHANGE.

v6.1.0
![image](https://user-images.githubusercontent.com/12452003/50565263-bbea3300-0d0b-11e9-8ced-f77a87b4a1ee.png)
v6.0.0
![image](https://user-images.githubusercontent.com/12452003/50565259-b12f9e00-0d0b-11e9-9e5e-1ca4ed56308c.png)

- goForward is totally broken.
never enabled
![image](https://user-images.githubusercontent.com/12452003/50565366-ee486000-0d0c-11e9-8bac-0e447bf60fab.png)

**Comment by supasate** [comment]
For the LOCATION_CHANGE calling after componentDidMount, this is intended to fix the old implementation by moving the dispatching from `constructor` to `componentDidMount`. (see this [comment](https://github.com/supasate/connected-react-router/pull/208#issuecomment-448169962).

For the goForward, can you explain a bit more? Is there any minimal repo to reproduce it?

**Comment by ahce** [comment]
@supasate Thanks for your reply!
[The repo](https://github.com/ahce/connected-react-router-610)
Use this [extension](https://chrome.google.com/webstore/detail/redux-saga-dev-tools/kclmpmjofefcpjlommdpokoccidafnbi) for test the sagas and actions.

**Comment by syjstc** [comment]
Got similar problem here, but backward. The problem is caused by the listeners of `react-router`'s history and the subscriber of `redux` store. 

`Router` component from `react-router` will listen to history in` componentWillMount`. (v 4.3.1 used by latest `connected-react-router`).
But `ConnectedRouter` will do that in `componentDidMount` instead of ` constructor`.
The order of these listeners are changed in 6.1.0.
Also, `ConnectedRouter` subscribes to redux store. It will check history path with store path.

Here is an example when browser backward is clicked:
The listener of router component will be triggered first. That will update it's state. Then children components might be updated, and fire some redux actions (from componentDidUpdate or others). Because redux executions are sync, so store could be changed, then subscribers will be triggered first before the history listener of `ConnectedRouter`. In that case, `LOCATION_CHANGE ` won't be fired the first time when a history is changed. But according to the subscriber, store path is still the old one. So a new `history.push` will be fired.  That's really unexpected.

**Comment by ryank311** [comment]
We saw really odd behavior as well in our application when upgrading to the latest version.  We had two pages, both with back buttons and we would somehow get into a circular loop.  

1. Page 0, click a link to Page 1
2. Page 1, click a link to Page 2
3. Page 2, click a button that calls (back) and navigate to Page 1
4. Page 1, click a button that calls (back) and navigate to Page 0

Works fine on version 6.0.0, but on version 6.1.0, step 4 actually gets sent to Page 2 instead of Page 0.  For now, we have reverted to the older stable version.

**Comment by supasate** [comment]
@ahce @syjstc @ryank311 Can you all try again with connected-react-router@next (6.2.0-beta.1) if it solves the problem?

**Comment by simontong** [comment]
@supasate  - That fixed it for me too, thanks

**Comment by nvma** [comment]
Wew, thought it was something on my end, spent couple of hours digging through the code. Upgrading to a current `6.2.0-beta.3` solved it. Much appreciated.

**Comment by chrispaynter** [comment]
Thank you for this fix, `6.2.0-beta.3` has saved my sanity.

**Comment by harrygreen** [comment]
We had the same issue - `6.2.0-beta.3` has solved it. Thanks @supasate!!

**Comment by j13l** [comment]
Had the same issue where components were mounted twice after `history.push`, lost 1/2 day debugging, `6.2.0-beta.3` fixes it. Thank you!

**Comment by chrispaynter** [comment]
I think this fix is important enough to get published into NPM with a hot fix.

**Comment by supasate** [comment]
v6.2.0 has been released :)
