### ISSUE TITLE
connected-react-router updates the URL, but does not update the component

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [supasate/connected-react-router#320]
Hi, I can not get this package to update the display component of the new data when I just click  **Link** component. It successfully updated the URL and even the Redux state, which can be seen in the localstorage, where this state is, is mirrored! But it doesn't update component and it's view =(

What is wrong with it?

I publish my App at Sandbox:
[![Edit cool-thunder-iblv0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-thunder-iblv0?fontsize=14)

**Comment by AlexandreArpin** [comment]
Thanks a lot for the Sandbox, it was really useful to debug.

The issue you're having has nothing to do with `connected-react-router`. The issue is that you're not using the `exact` attribute for your `Route`

```
<Switch>
  <Route path="/" exact component={Home} />
  <Route path="/authorization" exact component={Authorization} />
  <Route component={Whoops404} />
</Switch>
```

I debugged it by refreshing the `/authorization` URL and it was still showing `Home`. Since `/` is a subset of `/authorization`, it was always picking up `Home` as the component. By "hard refreshing" on `/authorization`, you can validate if the issue is `connected-react-router` related.

You can also remove `exact` and move the `/` lower in the list of `Route`

**Comment by Andrew-Dyachenko** [comment]
@AlexandreArpin It's awesome, you made my evening! More than once I got tired until I could find a problem. As you said, everything works out, just the router could not understand which component to output to it. Thank you very much!

**Comment by AlexandreArpin** [comment]
@Andrew-Dyachenko no problems!

Don't forget to close the issue.

**Comment by Andrew-Dyachenko** [comment]
Solved! Pick exact route path to describe router what exactly to render! )
